.TH DEVMAP_NAME 8 "July 2006" "" "Linux Administrator's Manual"
.SH NAME
devmap_name \- Query device-mapper name
.SH SYNOPSIS
.B devmap_name
.RB [\| \-l\ \c
.IR seconds \|]
.RB [\| \-t\ \c
.IR type \|]
.RB [\| \-v \|]
.RB [\| device \]
.SH DESCRIPTION
.B devmap_name
queries the device-mapper for the name for the device
specified by
.I device.
The device can be given either 
.I major minor
or
.I major:minor
number. It will only return the name if the device is accessible.
.br
.B devmap_name
can be called from
.B udev
by the following rule in
.IR /etc/udev/udev.rules :
.sp
.nf
KERNEL="dm-[0-9]*", PROGRAM="/sbin/devmap_name %M %m", \\
	NAME="%k", SYMLINK="%c"
.fi
.SH OPTIONS
.TP
.B \-l \fIseconds\fB
Number of seconds to wait before timeout on an inaccessible
device-mapper device.
.TP
.B \-t \fItype\fB
Only print table name for device-mapper tables of type
.I type
.TP
.B \-v
Verbose output

.SH "SEE ALSO"
.BR udev (8),
.BR dmsetup (8)
.SH AUTHORS
.B devmap_name
was developed by Christophe Varoqui, <christophe.varoqui@free.fr> and others.
