name: compile and unit test on native arch
on:
  push:
    branches:
      - exp

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [buster, jessie, sid, alpine]
        arch: ['', '-i386']
    container: mwilck/multipath-build-${{ matrix.os }}${{ matrix.arch }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build and test
        run: make test

