name: compile and unit test on ppc64le
on:
  push:
    branches: [exp]
jobs:
  build:
    runs-on: ubuntu-20.04
    container: mwilck/multipath-build-buster-ppc64le
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make test-progs
      - name: archive
        run: >
          tar cfv binaries.tar
          Makefile*
          libmpathcmd/*.so* libmultipath/*.so*
          tests/lib tests/*-test tests/Makefile tests/*.so*
      - uses: actions/upload-artifact@v1
        with:
          name: multipath-ppc64le
          path: binaries.tar
  run:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: get binaries
        uses: actions/download-artifact@v1
        with:
          name: multipath-ppc64le
      - name: unpack
        run: tar xfv multipath-ppc64le/binaries.tar
      - name: enable ppc64le arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: run tests
        uses: docker://mwilck/multipath-run-buster-ppc64le
        with:
          args: -C tests
