name: compile and unit test on s390x
on:
  push:
    branches: [exp]
jobs:
  prep:
    runs-on: ubuntu-20.04
    steps:
      - name: check
        run: |
          sudo apt-get update
          sudo systemctl status docker
          pwd
          ls -l
      - name: install
        run: |
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          ls -l /proc/sys/fs/binfmt_misc/
          sudo docker run --rm -t ppc64le/busybox uname -m
          docker run --rm -t ppc64le/busybox uname -m
  build:
    runs-on: ubuntu-20.04
    container: mwilck/multipath-build-buster-s390x
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: look
        run: ls -l
