name: compile and unit test on s390x
on:
  push:
    branches: [exp]
jobs:
  build:
    runs-on: ubuntu-20.04
    container: mwilck/multipath-build-buster-s390x
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make test-progs
      - name: archive
        run: >
          tar cfv s390x.tar
          Makefile*
          libmpathcmd/*.so* libmultipath/*.so*
          tests/lib tests/*-test tests/Makefile tests/*.so*
      - uses: actions/upload-artifact@v1
        with:
          name: multipath-s390x
          path: s390x.tar
  run:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: get binaries
        uses: actions/download-artifact@v1
        with:
          name: multipath-s390x
      - name: unpack
        run: tar xfv multipath-s390x/s390x.tar
      - name: enable s390 arch
        run: sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: run tests
        uses: docker://mwilck/multipath-run-buster-s390x
